export const TRANSPILE_STATUS = {
  START: "START",
  END: "END",
  ADD_DEPENDENCY: "ADD_DEPENDENCY",
  TRANSPILE_DEPENDENCY: "TRANSPILE_DEPENDENCY",
  ERROR: "ERROR",
};

export const TRANSPILE_ERROR = {
  DEPENDENCY_NOT_FOUND: "DEPENDENCY_NOT_FOUND",
};
